#*******************************************************************************
#.travis.yml
#*******************************************************************************


#Purpose:
#Travis CI is a hosted continuous integration service, that is, it allows 
#running code directly from a repository and checking that the code acts as 
#expected. The purpose of the .travis.yml file is to give instructions to Travis 
#CI on how to do the work.
#Author:
#Cedric H. David, 2017-2018


sudo: required

language: generic

services:
  - docker

env:
  - test_result=0

install:
  - docker build -t shbaam .

before_script:
  - docker run shbaam

script:
  - if [ $test_result -eq 0 ]; then echo "wtf?"; fi
  - if [ $test_result -eq 0 ]; then echo "1" && echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin; fi
  - if [ $test_result -eq 0 ]; then echo "1" && docker tag shbaam $DOCKER_USERNAME/shbaam; fi
  - if [ $test_result -eq 0 ]; then echo "1" && docker push $DOCKER_USERNAME/shbaam; fi

#*******************************************************************************
#End
#*******************************************************************************
