#*******************************************************************************
#.travis.yml
#*******************************************************************************


#Purpose:
#Travis CI is a hosted continuous integration service, that is, it allows 
#running code directly from a repository and checking that the code acts as 
#expected. The purpose of the .travis.yml file is to give instructions to Travis 
#CI on how to do the work.
#Author:
#Cedric H. David, 2017-2018


sudo: required

language: generic

services:
  - docker

before_script:
  - docker build -t shbaam .
  - docker run shbaam

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker tag shbaam $DOCKER_USERNAME/shbaam
  - docker push $DOCKER_USERNAME/shbaam

#*******************************************************************************
#End
#*******************************************************************************
