#*******************************************************************************
#.travis.yml
#*******************************************************************************


#Purpose:
#Travis CI is a hosted continuous integration service, that is, it allows 
#running code directly from a repository and checking that the code acts as 
#expected. The purpose of the .travis.yml file is to give instructions to Travis 
#CI on how to do the work.
#Author:
#Cedric H. David, 2017-2018


sudo: required

language: generic

services:
  - docker

env:
  - PROJECT_NAME="shbaam"
  - TAG="$DOCKER_USERNAME/$PROJECT_NAME"

before_script:
  - docker build -t  .
  - docker run $PROJECT_NAME

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker TAG "$PROJECT_NAME" "$DOCKER_USERNAME/$PROJECT_NAME"
  - docker push "$DOCKER_USERNAME/$PROJECT_NAME"

#*******************************************************************************
#End
#*******************************************************************************
